const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/candidate/login', (req, res) => res.render('pages/candidate/login'))
  .get('/candidate/singup', (req, res) => res.render('pages/candidate/signup'))
  .get('/candidate/gallery', (req, res) => res.render('pages/candidate/gallery'))
  .get('/recruiter/login', (req, res) => res.render('pages/recruiter/login'))
  .get('/recruiter/singup', (req, res) => res.render('pages/recruiter/signup'))
  .get('/recruiter/gallery', (req, res) => res.render('pages/recruiter/gallery'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
